export const SCREENS = {
    PHONE_NO: 'PHONE_NO',
    OTP: "OTP",
    CREATE_PIN: "CREATE_PIN",
    CREATE_USER_NAME: "CREATE_USER_NAME",
    ENTER_PIN: "ENTER_PIN",
    SCAN_BIOMETRIC: "SCAN_BIOMETRIC"
  };