export const SCREENS = {
    PHONE_NO: 'PHONE_NO',
    OTP: "OTP",
    CREATE_PIN: "CREATE_PIN",
    CREATE_USER_NAME: "CREATE_USER_NAME",
    ENTER_PIN: "ENTER_PIN",
    SCAN_BIOMETRIC: "SCAN_BIOMETRIC",
    ONBOARDING: "ONBOARDING",
    LOGIN: "LOGIN",
    ENTER_USER_NAME: "ENTER_USER_NAME",
    HOME: "HOME",
    SELECT_PURPOSE: "SELECT_PURPOSE",
    PROCEED_PAYMENT: "PROCEED_PAYMENT",
    BENEFICIARY_CARD_DETAIL: "BENEFICIARY_CARD_DETAIL"
  };